import { PrismaClient } from '@prisma/client';

export async function seedEmployees(prisma: PrismaClient) {
  const employees = [
    {
      oracleId: 'EMP-001',
      employeeNumber: '10001',
      firstName: 'John',
      lastName: 'Smith',
      displayName: 'John Smith',
      email: 'john.smith@example.com',
      status: 'ACTIVE',
      departmentId: '100',
    },
    {
      oracleId: 'EMP-002',
      employeeNumber: '10002',
      firstName: 'Sarah',
      lastName: 'Wilson',
      displayName: 'Sarah Wilson',
      email: 'sarah.wilson@example.com',
      status: 'ACTIVE',
      departmentId: '200',
    },
    {
      oracleId: 'EMP-003',
      employeeNumber: '10003',
      firstName: 'Michael',
      lastName: 'Brown',
      displayName: 'Michael Brown',
      email: 'michael.brown@example.com',
      status: 'ACTIVE',
      departmentId: '300',
    },
    {
      oracleId: 'EMP-004',
      employeeNumber: '10004',
      firstName: 'Emily',
      lastName: 'Davis',
      displayName: 'Emily Davis',
      email: 'emily.davis@example.com',
      status: 'ACTIVE',
      departmentId: '400',
    },
    {
      oracleId: 'EMP-005',
      employeeNumber: '10005',
      firstName: 'David',
      lastName: 'Miller',
      displayName: 'David Miller',
      email: 'david.miller@example.com',
      status: 'ACTIVE',
      departmentId: '100',
    },
    {
      oracleId: 'EMP-006',
      employeeNumber: '10006',
      firstName: 'Jessica',
      lastName: 'Taylor',
      displayName: 'Jessica Taylor',
      email: 'jessica.taylor@example.com',
      status: 'ACTIVE',
      departmentId: '200',
    },
    {
      oracleId: 'EMP-007',
      employeeNumber: '10007',
      firstName: 'Robert',
      lastName: 'Anderson',
      displayName: 'Robert Anderson',
      email: 'robert.anderson@example.com',
      status: 'ACTIVE',
      departmentId: '300',
    },
    {
      oracleId: 'EMP-008',
      employeeNumber: '10008',
      firstName: 'Linda',
      lastName: 'Thomas',
      displayName: 'Linda Thomas',
      email: 'linda.thomas@example.com',
      status: 'ACTIVE',
      departmentId: '400',
    },
    {
      oracleId: 'EMP-009',
      employeeNumber: '10009',
      firstName: 'James',
      lastName: 'Jackson',
      displayName: 'James Jackson',
      email: 'james.jackson@example.com',
      status: 'ACTIVE',
      departmentId: '100',
    },
    {
      oracleId: 'EMP-010',
      employeeNumber: '10010',
      firstName: 'Patricia',
      lastName: 'White',
      displayName: 'Patricia White',
      email: 'patricia.white@example.com',
      status: 'ACTIVE',
      departmentId: '200',
    },
    {
      oracleId: 'EMP-011',
      employeeNumber: '10011',
      firstName: 'William',
      lastName: 'Harris',
      displayName: 'William Harris',
      email: 'william.harris@example.com',
      status: 'ACTIVE',
      departmentId: '300',
    },
    {
      oracleId: 'EMP-012',
      employeeNumber: '10012',
      firstName: 'Elizabeth',
      lastName: 'Martin',
      displayName: 'Elizabeth Martin',
      email: 'elizabeth.martin@example.com',
      status: 'ACTIVE',
      departmentId: '400',
    },
    {
      oracleId: 'EMP-013',
      employeeNumber: '10013',
      firstName: 'Christopher',
      lastName: 'Thompson',
      displayName: 'Christopher Thompson',
      email: 'christopher.thompson@example.com',
      status: 'ACTIVE',
      departmentId: '100',
    },
    {
      oracleId: 'EMP-014',
      employeeNumber: '10014',
      firstName: 'Jennifer',
      lastName: 'Garcia',
      displayName: 'Jennifer Garcia',
      email: 'jennifer.garcia@example.com',
      status: 'ACTIVE',
      departmentId: '200',
    },
    {
      oracleId: 'EMP-015',
      employeeNumber: '10015',
      firstName: 'Daniel',
      lastName: 'Martinez',
      displayName: 'Daniel Martinez',
      email: 'daniel.martinez@example.com',
      status: 'ACTIVE',
      departmentId: '300',
    },
    {
      oracleId: 'EMP-016',
      employeeNumber: '10016',
      firstName: 'Mary',
      lastName: 'Robinson',
      displayName: 'Mary Robinson',
      email: 'mary.robinson@example.com',
      status: 'ACTIVE',
      departmentId: '400',
    },
    {
      oracleId: 'EMP-017',
      employeeNumber: '10017',
      firstName: 'Matthew',
      lastName: 'Clark',
      displayName: 'Matthew Clark',
      email: 'matthew.clark@example.com',
      status: 'ACTIVE',
      departmentId: '100',
    },
    {
      oracleId: 'EMP-018',
      employeeNumber: '10018',
      firstName: 'Susan',
      lastName: 'Rodriguez',
      displayName: 'Susan Rodriguez',
      email: 'susan.rodriguez@example.com',
      status: 'ACTIVE',
      departmentId: '200',
    },
    {
      oracleId: 'EMP-019',
      employeeNumber: '10019',
      firstName: 'Anthony',
      lastName: 'Lewis',
      displayName: 'Anthony Lewis',
      email: 'anthony.lewis@example.com',
      status: 'ACTIVE',
      departmentId: '300',
    },
    {
      oracleId: 'EMP-020',
      employeeNumber: '10020',
      firstName: 'Karen',
      lastName: 'Lee',
      displayName: 'Karen Lee',
      email: 'karen.lee@example.com',
      status: 'ACTIVE',
      departmentId: '400',
    },
  ];

  for (const employee of employees) {
    const department = await prisma.department.findUnique({
      where: {
        oracleId: employee.departmentId,
      },
    });

    if (!department) {
      continue;
    }

    await prisma.employee.upsert({
      where: {
        oracleId: employee.oracleId,
      },

      update: {
        employeeNumber: employee.employeeNumber,
        firstName: employee.firstName,
        lastName: employee.lastName,
        displayName: employee.displayName,
        email: employee.email,
        departmentId: department.id,
      },

      create: {
        oracleId: employee.oracleId,
        employeeNumber: employee.employeeNumber,
        firstName: employee.firstName,
        lastName: employee.lastName,
        displayName: employee.displayName,
        email: employee.email,
        status: employee.status,
        departmentId: department.id,
      },
    });
  }

  console.log(`Employee seeded: ${employees.length}`);
}
